---
credentials:
  user: Administrator
  password: V3rsa@321
  headers:
    Accept: application/json
    Content-Type: application/json
  return_content: yes
  force_basic_auth: yes
  validate_certs: no
  follow_redirects: all
  timeout: 60
